"""
Data models for SupplyGuard AI.
Uses pure Python standard library dataclasses for lean, zero-bloat execution.
"""

from dataclasses import dataclass, field, asdict
from enum import Enum
from pathlib import Path
from typing import Dict, Any, List, Optional
import datetime


class SeverityLevel(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class FindingCategory(str, Enum):
    EXPOSED_SECRET = "EXPOSED_SECRET"
    DEPENDENCY_REPRODUCIBILITY_RISK = "DEPENDENCY_REPRODUCIBILITY_RISK"
    INSTALL_HOOK = "INSTALL_HOOK"
    DANGEROUS_EXECUTION = "DANGEROUS_EXECUTION"
    CONFIG_ISSUE = "CONFIG_ISSUE"


@dataclass
class SecurityFinding:
    """Represents an isolated, evidence-backed security finding detected by a local scanner."""
    id: str
    category: FindingCategory
    severity: SeverityLevel
    title: str
    description: str
    file_path: str
    line_number: Optional[int] = None
    snippet: Optional[str] = None  # Always masked / redacted before assignment
    explanation: str = ""
    remediation: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data["category"] = self.category.value
        data["severity"] = self.severity.value
        return data


@dataclass
class RiskChain:
    """
    Represents correlated findings linked via deterministic rules.
    Explains the attack path and combined risk rather than isolated alerts.
    """
    id: str
    rule_id: str
    title: str
    composite_severity: SeverityLevel
    risk_priority_score: float  # SupplyGuard Risk Priority Score (0.0 - 10.0 heuristic)
    finding_ids: List[str]  # References IDs of the constituent SecurityFinding objects
    attack_vector: str
    rationale: str
    description: str = ""
    remediation_order: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data["composite_severity"] = self.composite_severity.value
        return data


@dataclass
class AIAnalysisResult:
    """
    Structured response generated by the reasoning layer (deterministic offline or local LLM).
    Receives only structured findings and risk chains — never raw source code.
    """
    executive_summary: str
    priority_risks: List[Dict[str, Any]] = field(default_factory=list)
    remediation_order: List[str] = field(default_factory=list)
    correlated_risks: List[Dict[str, Any]] = field(default_factory=list)
    potential_impacts: List[Dict[str, Any]] = field(default_factory=list)
    remediation_priorities: List[Dict[str, Any]] = field(default_factory=list)
    evidence_references: List[str] = field(default_factory=list)
    limitation_notice: str = (
        "Notice: This assessment is generated from local static signals and heuristic correlation. "
        "It does not guarantee exploitability or package malice, nor does it replace comprehensive code audit."
    )
    provider_used: str = "deterministic-offline"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class ScanReport:
    """Aggregated output of a project scan, ready for UI display or JSON export."""
    project_name: str
    ecosystem: str = "Node.js"
    scanned_files_count: int = 0
    dependencies_count: int = 0
    raw_findings: List[SecurityFinding] = field(default_factory=list)
    risk_chains: List[RiskChain] = field(default_factory=list)
    overall_risk_score: float = 0.0  # Heuristic SupplyGuard Risk Priority Score (0.0 - 10.0)
    ai_assessment: Optional[AIAnalysisResult] = None
    scan_duration_ms: float = 0.0
    scan_timestamp: str = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc).isoformat())

    @property
    def severity_counts(self) -> Dict[str, int]:
        counts = {s.value: 0 for s in SeverityLevel}
        for f in self.raw_findings:
            counts[f.severity.value] += 1
        return counts

    def to_dict(self) -> Dict[str, Any]:
        return {
            "project_name": self.project_name,
            "ecosystem": self.ecosystem,
            "scanned_files_count": self.scanned_files_count,
            "dependencies_count": self.dependencies_count,
            "severity_counts": self.severity_counts,
            "raw_findings": [f.to_dict() for f in self.raw_findings],
            "risk_chains": [rc.to_dict() for rc in self.risk_chains],
            "overall_risk_score": self.overall_risk_score,
            "ai_assessment": self.ai_assessment.to_dict() if self.ai_assessment else None,
            "scan_duration_ms": self.scan_duration_ms,
            "scan_timestamp": self.scan_timestamp,
        }


@dataclass
class ProjectContext:
    """Represents the ingested project file structure and discovered metadata."""
    project_name: str
    root_path: Path
    detected_ecosystems: List[str] = field(default_factory=list)
    all_discovered_files: List[Path] = field(default_factory=list)
    relevant_files: List[Path] = field(default_factory=list)
    total_file_count: int = 0
    relevant_file_count: int = 0
    temp_dir_obj: Optional[Any] = None

    def cleanup(self) -> None:
        """Safely cleans up temporary extraction directory if one was created."""
        if self.temp_dir_obj is not None:
            try:
                self.temp_dir_obj.cleanup()
            except Exception:
                pass
            self.temp_dir_obj = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "project_name": self.project_name,
            "root_path": str(self.root_path),
            "detected_ecosystems": self.detected_ecosystems,
            "all_discovered_files": [str(p) for p in self.all_discovered_files],
            "relevant_files": [str(p) for p in self.relevant_files],
            "total_file_count": self.total_file_count,
            "relevant_file_count": self.relevant_file_count,
        }
